name: Sync Repositories
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Clone source repository from GitHub
      run: |
        git clone --mirror https://github.com/kahiin-project/kahiin-db.git github-repo
    - name: Push to Codeberg repository
      env:
        CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
        CODEBERG_PASSWORD: ${{ secrets.CODEBERG_PASSWORD }}
      run: |
        cd github-repo
        git remote add codeberg https://${CODEBERG_USERNAME}:${CODEBERG_PASSWORD}@codeberg.org/tristan-gscn/kahiin-db.git
        git push --mirror codeberg
